/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiForecastRouteImport } from './routes/api/forecast'
import { Route as ApiFramesRouteImport } from './routes/api/frames'
import { Route as ApiSimeparRouteImport } from './routes/api/simepar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiForecastRoute = ApiForecastRouteImport.update({
  id: '/api/forecast',
  path: '/api/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFramesRoute = ApiFramesRouteImport.update({
  id: '/api/frames',
  path: '/api/frames',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimeparRoute = ApiSimeparRouteImport.update({
  id: '/api/simepar',
  path: '/api/simepar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/forecast': typeof ApiForecastRoute
  '/api/frames': typeof ApiFramesRoute
  '/api/simepar': typeof ApiSimeparRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/forecast': typeof ApiForecastRoute
  '/api/frames': typeof ApiFramesRoute
  '/api/simepar': typeof ApiSimeparRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/forecast': typeof ApiForecastRoute
  '/api/frames': typeof ApiFramesRoute
  '/api/simepar': typeof ApiSimeparRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/forecast' | '/api/frames' | '/api/simepar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/forecast' | '/api/frames' | '/api/simepar'
  id: '__root__' | '/' | '/api/forecast' | '/api/frames' | '/api/simepar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiForecastRoute: typeof ApiForecastRoute
  ApiFramesRoute: typeof ApiFramesRoute
  ApiSimeparRoute: typeof ApiSimeparRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/forecast': {
      id: '/api/forecast'
      path: '/api/forecast'
      fullPath: '/api/forecast'
      preLoaderRoute: typeof ApiForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/frames': {
      id: '/api/frames'
      path: '/api/frames'
      fullPath: '/api/frames'
      preLoaderRoute: typeof ApiFramesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/simepar': {
      id: '/api/simepar'
      path: '/api/simepar'
      fullPath: '/api/simepar'
      preLoaderRoute: typeof ApiSimeparRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiForecastRoute: ApiForecastRoute,
  ApiFramesRoute: ApiFramesRoute,
  ApiSimeparRoute: ApiSimeparRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
